[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:;"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Serve pitch.html at /pitch
[[redirects]]
  from = "/pitch"
  to = "/pitch.html"
  status = 200
  force = true

[[redirects]]
  from = "/pitch/*"
  to = "/pitch.html"
  status = 200
  force = true

# Serve signature.html at /signature  
[[redirects]]
  from = "/signature"
  to = "/signature.html"
  status = 200
  force = true

[[redirects]]
  from = "/signature/*"
  to = "/signature.html"
  status = 200
  force = true
